---
server:
  port: 0
spring:
  cloud:
    iot:
      gateway:
        rest:
          enabled: true
---
spring:
  profiles: coap
  cloud:
    stream:
      coap:
        binder:
          mode: INBOUND_GATEWAY
      bindings:
        iotGatewayServer:
          binder: coap
          producer:
            useNativeEncoding: true
---
spring:
  profiles: xbee
  cloud:
    iot:
      xbee:
        enabled: true
        serialPort: /dev/ttyUSB0
    stream:
      xbee:
        binder:
          mode: INBOUND_GATEWAY
      bindings:
        iotGatewayServer:
          binder: xbee
          producer:
            useNativeEncoding: true
        