---
server:
  port: 0
spring:
  cloud:
    iot:
      gateway:
        rest:
          enabled: true
---
spring:
  profiles: coap
---
spring:
  profiles: xbee
  cloud:
    iot:
      xbee:
        enabled: true
        serialPort: /dev/ttyUSB0
