game:
  total: 12
spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        button1:
          button:
            properties:
              id: 0x80
            enabled: true
            gpio:
              pin: 24
              reference: GND
        button2:
          button:
            properties:
              id: 0x40
            enabled: true
            gpio:
              pin: 23
              reference: GND
        button3:
          button:
            properties:
              id: 0x20
            enabled: true
            gpio:
              pin: 25
              reference: GND
        button4:
          button:
            properties:
              id: 0x10
            enabled: true
            gpio:
              pin: 12
              reference: GND
        led1:
          led:
            enabled: true
            gpio:
              pin: 17
        led2:
          led:
            enabled: true
            gpio:
              pin: 18
        led3:
          led:
            enabled: true
            gpio:
              pin: 27
        led4:
          led:
            enabled: true
            gpio:
              pin: 22
        buzzer:
          buzzer:
            enabled: true
            type: ACTIVE
            gpio:
              pin: 26
      raspberry:
        numberingScheme: BROADCOM
