spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        myPotentiometer:
          potentiometer:
            enabled: true
            min: 0
            max: 255
            i2c:
              bus: 1
              address: 0x48
      raspberry:
        numberingScheme: BROADCOM 
