spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        myPotentiometer:
          potentiometer:
            enabled: true
            i2c:
              bus: 1
              address: 0x48
              min: 0
              max: 255
      raspberry:
        numberingScheme: BROADCOM 
