spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        myButton:
          button:
            enabled: true
            gpio:
              pin: 18
        myLed:
          led:
            enabled: true
            illuminateOnStart: false
            illuminateOnExit: false
            gpio:
              pin: 17
      raspberry:
        numberingScheme: BROADCOM
