management:
  security:
    enabled: false
spring:
  cloud:
    iot:
      device:
        lcd:
          rows: 2
          colums: 16
          clearTextOnExit: true
      platform: RASPBERRY
      raspberry:
        numberingScheme: BROADCOM
      i2c:
        addresses:
          0x27:
            bus: 1
            type: lcd
