spring:
  cloud:
    iot:
      platform: RASPBERRY
      gpio:
        pins:
          17:
            type: DIMMEDLED
          18:
            type: DIMMEDLED
      raspberry:
        numberingScheme: BROADCOM
