spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        myButton:
          button:
            gpio:
              pin: 17
        myDimmedLedRed:
          dimmedLed:
            gpio:
              pin: 18
        myDimmedLedGreen:
          dimmedLed:
            gpio:
              pin: 27
      raspberry:
        numberingScheme: BROADCOM
