spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        myButton:
          button:
            enabled: true
            gpio:
              pin: 27
        myRotary:
          incrementalRotary:
            enabled: true
            incrementSteps: 20
            gpio:
              leftPin: 17
              rightPin: 18
              clickPin: 27
      raspberry:
        numberingScheme: BROADCOM
