spring:
  cloud:
    iot:
      components:
        myHumiditySensor:
          humidity:
            enabled: true
            gpio:
              pin: 17
      metrics:
        boot:
          enabled: true
      platform: RASPBERRY
      raspberry:
        numberingScheme: BROADCOM
