logging:
  level:
    org.springframework.cloud.iot: DEBUG
spring:
  cloud:
    iot:
      platform: RASPBERRY
      components:
        myHumiditySensor:
          humidity:
            enabled: true
            gpio:
              pin: 17
      raspberry:
        numberingScheme: BROADCOM
