---
server:
  port: 0
spring:
  cloud:
    iot:
      gateway:
        rest:
          enabled: true
---
spring:
  profiles: coap
  cloud:
    stream:
      coap:
        binder:
          mode: OUTBOUND_GATEWAY
      bindings:
        iotGatewayClient:
          binder: coap
          producer:
            useNativeEncoding: true
---
spring:
  profiles: xbee
  cloud:
    iot:
      xbee:
        enabled: true
        serialPort: /dev/ttyUSB0
    stream:
      bindings:
        iotGatewayClient:
          binder: xbee
          producer:
            useNativeEncoding: true
