logging:
  level:
    org.springframework.cloud.iot: DEBUG
management:
  security:
    enabled: false
spring:
  cloud:
    iot:
      mqtt:
        addresses: localhost:1883
        username: scdf
        password: scdf
      metrics:
        boot:
          enabled: true
        mqtt:
          export:
            enabled: true
        coap:
          export:
            enabled: true
