spring:
  cloud:
    iot:
      mqtt:
        addresses: localhost:1883
        username: scdf
        password: scdf
      metrics:
        boot:
          enabled: true
        mqtt:
          export:
            enabled: false
        coap:
          export:
            enabled: false
