management:
  security:
    enabled: false
spring:
  cloud:
    iot:
      mqtt:
        addresses: localhost:1883
        username: scdf
        password: scdf
      metrics:
        mqtt:
          export:
            enabled: false
        coap:
          export:
            enabled: true
